name: Check & Lint
on:
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check & Lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install
        run: npm install
      - name: deps
        run: npm ci
      - name: check
        run: npm run check
      - name: lint
        run: npm run lint
